# ema Makefile (dev-only; the `ema` CLI and the MariaDB data-dir init script
# init-cluster.sh are also shipped via Composer for consumers — see
# "Standalone template usage" in the README).

SHELL := $(shell which bash 2>/dev/null)

# Machine paths are derived from the repo root and owned by this Makefile
# (not by the environment). ema has no .env: the per-instance dev connection
# config lives in var/sandbox/<name>-<guid>/reuter.ini (generated by
# `ema sandbox`), never in a shell export. The defaults let every target run
# standalone, e.g. `make dev-init` via ssh where no env vars exist.
REPO_PATH = $(CURDIR)
REPO_VAR = $(REPO_PATH)/var
REPO_LOG = $(REPO_VAR)/log

.PHONY: help dev-init _dev-assert-nix _dev-init _dev-create-dirs

help:
	@echo "Available initialization targets:"
	@echo "  dev-init   - Prepare the dev working dirs (run inside 'nix develop')"

dev-init: _dev-assert-nix _dev-init

_dev-assert-nix:
	@if [ -z "$$IN_NIX_SHELL" ]; then \
		echo "ERROR: This target must be run inside 'nix develop'"; \
		exit 1; \
	fi

_dev-init: _dev-create-dirs
	@echo "Developer environment successfully initialized."

_dev-create-dirs:
	@echo "Creating local logging and storage directories..."
	mkdir -p $(REPO_LOG)
