# ema Makefile (dev-only; the `ema` CLI and the MariaDB dev-init script
# init-cluster.sh are also shipped in the nix package for consumers — see
# "Standalone template usage" in the README).

SHELL := $(shell which bash 2>/dev/null)

# Machine paths are derived from the repo root and owned by this Makefile
# (not by the environment). ema has no .env: the dev connection config lives
# in var/reuter.local.ini (generated by `ema init db`), never in a shell
# export. The defaults let every target run standalone, e.g. `make dev-init`
# via ssh where no env vars exist.
REPO_PATH = $(CURDIR)
REPO_VAR = $(REPO_PATH)/var
REPO_LOG = $(REPO_VAR)/log
MYSQL_BASE_DIR = $(REPO_VAR)/mariadb
MYSQL_DATA_DIR = $(MYSQL_BASE_DIR)/data
MYSQL_UNIX_PORT = $(MYSQL_BASE_DIR)/mysql.sock
MYSQL_PID_FILE = $(MYSQL_BASE_DIR)/mysql.pid

.PHONY: help dev-init _dev-assert-nix _dev-init _dev-create-dirs _dev-init-cluster

help:
	@echo "Available initialization targets:"
	@echo "  dev-init   - Run ONCE after cloning locally to build the dev sandbox"

dev-init: _dev-assert-nix _dev-init

_dev-assert-nix:
	@if [ -z "$$IN_NIX_SHELL" ]; then \
		echo "ERROR: This target must be run inside 'nix develop'"; \
		exit 1; \
	fi

_dev-init: _dev-create-dirs _dev-init-cluster
	@echo "Developer environment successfully initialized."

_dev-create-dirs:
	@echo "Creating local logging and storage directories..."
	mkdir -p $(REPO_LOG) $(MYSQL_DATA_DIR)

_dev-init-cluster:
	@bin/dev/init-cluster.sh "$(MYSQL_DATA_DIR)" "$(MYSQL_PID_FILE)" "$(MYSQL_UNIX_PORT)"
